apiVersion: v1
kind: Service
metadata:
  name: workflow-frontend
  namespace: default
spec:
  selector:
    app: workflow-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer # Hoặc ClusterIP nếu dùng Ingress
